### ISSUE TITLE
Berserker Rage generates way too much rage upon hit

### ISSUE THREAD

**Issue by marrowwow** [magey/wotlk-warrior#10]
#### 1.1. Description
Berserker Rage (BR) is supposed to give you some more additional rage upon receiving damage. In it's current state, however, it generates 100 rage instantly.

  #### 1.2. How to Reproduce
           1. Get hit by a mob. Record amount of rage received.
           2. Use BR.
           3. Watch as your rage bar instantly fills up to 100.
           
#### 2.1. Description

BR should generate additional rage, but not to this extent.

Tested on Version: 3.4.0.44369.

**Comment by Aggrend** [comment]
I believe this is resolved as of build 44510 or later.

**Comment by magey** [comment]
Can confirm it's fixed (tested now on 44644)
