### ISSUE TITLE
AoE damage caps are wrong

### ISSUE THREAD

**Issue by magey** [magey/wotlk-warrior#13]
Patch 3.3.5 should have a 10-target AoE damage cap as described [here](https://gist.github.com/magey/dcfe8818889e30af9c97345a43976dfd#file-wotlk-patch-txt-L1227):

```
  * Area-of-Effect Damage Caps: We've redesigned the way area damage is
    capped when hitting many targets. Instead of a hard cap on total
    damage done, the game now caps the total damage done at a value
    equal to the damage the spell would do if it hit 10 targets. In
    other words, a spell normally hits each target for 1000 damage. With
    3 targets, the multiplier is 1, so it doesn't change. Same with 10
    targets. With 20 targets, the multiplier is 10/20=0.5. So, it hits
    for 0.5*1000=500.
```

Meaning that the total damage an AoE spell can do is capped as if it hit 10 targets. If it hits more than 10 targets, the damage it would have done to 10 targets is split evenly among all the targets it actually hits.

Testing on build 44644 on both Warrior and Mage revealed that on beta the AoE damage cap is 20 targets instead 10, a change that was introduced in [MoP (patch 5.2)](https://web.archive.org/web/20140122203357/http://us.battle.net/wow/en/blog/8896363/):

```
Area Damage Cap: The area damage cap is now 20 targets (was 10). This
means area of effect damage spells now reach their maximum damage when
striking 20 targets. If more than 20 targets are struck, then the total
damage done is spread evenly over the actual number of targets present.
```
---
**Mage / Blizzard**

[mage_blizzard_20_and_26_targets.txt](https://github.com/magey/wotlk-warrior/files/9106487/mage_blizzard_20_and_26_targets.txt)

For this test a single tick of Blizzard on a single target hit for 344 (this is our reference value). I tested various numbers of targets and Blizzard always ticked for 344 on all targets up to (and including) 20 targets. Once I went past 20 targets then I started seeing the AoE caps taking effect. In the attached log there are two test cases; one with 20 targets where Blizzard ticks for 344 and one with 26 targets where it ticks between 264 and 265. We can arrive at this value by using the method described in the patch notes:
```
multiplier = 20/26 = ~0.76923
final_damage = 344 * multiplier = 344 * 0.76923 = 264.61512
```

**Warrior / Thunder Clap**

[warrior_thunder_clap_20_and_26_targets.txt](https://github.com/magey/wotlk-warrior/files/9106531/warrior_thunder_clap_20_and_26_targets.txt)

For this test a single raw (pre-mitigation) hit of Thunder Clap rank 7 on a single target hit for 397. This value matches up with the character's stats and talents, and coincidentally verified Thunder Clap's 12% AP coefficient:

```
attack_power = 902
base_damage = 184 + 902*0.12 = 292.24

improved_thunder_clap = 1.3
defensive_stance = 0.95
one_handed_weapon_spec = 1.10

final_raw_damage = 292.24 * 1.3 * 0.95 * 1.10 = 397.00804
```

Again I did many tests with varying number of targets, and we can see the same behavior as the Mage test in this log; at exactly 20 targets all of them are hit for 397 raw, while at 26 targets they are hit for 305 raw. Calculating again using the patch notes method:

```
multiplier = 20/26 = ~0.76923
final_damage = 397 * multiplier = 397 * 0.76923 = 305.38431
```

**Comment by yurpcraft** [comment]
Additional data from mages here: https://github.com/JamminL/wotlk-classic-bugs/issues/254

**Comment by magey** [comment]
Fixed in build 45043.
