### ISSUE TITLE
Hit suppression is still present

### ISSUE THREAD

**Issue by magey** [magey/wotlk-warrior#16]
The hit suppression that was present in vanilla and TBC was removed with WotLK; this suppression kicked in when the difference between the target's defense and the attacker's weapon skill was greater than 10, and the formula for determining the amount of suppression was:

```
hit_suppression = (target_defense - attacker_weapon_skill - 10) * 0.2%
```

Which meant that a max level player attacking a boss mob 3 levels higher had -1% suppression to their hit chance (in the case of vanilla, assume no extra weapon skill to simplify the example). In turn this meant that even though the miss chance was 8%, the hit cap was 9% as you needed one extra hit% to overcome the suppression.

With WotLK this should all be gone - no suppression is present anymore and the hit cap is 8%, as verified multiple times in the [Retesting hit table assumptions](https://web.archive.org/web/20100808151333/http://elitistjerks.com/f78/t38095-retesting_hit_table_assumptions/#post999574) EJ thread we keep coming back to every beta.

Unfortunately, currently on beta build 44644 the suppression is still present as can be see from these screenshots:

![image](https://user-images.githubusercontent.com/44882404/179434249-20d0e211-03fd-4eec-bae2-709c81ccc4be.png)

![image](https://user-images.githubusercontent.com/44882404/179434280-dea339c2-c36c-4092-a053-324b5d1fdbd3.png)

My level 80 warrior has 400 weapon skill and attacking the Heroic Training Dummy which has 415 defense, wielding a 1H mace and a shield. Additionally as can be seen above I have 263 hit rating which translates to 8.02% hit, which should make it impossible to miss an attack in this scenario.

**Comment by Aggrend** [comment]
This should be fixed in our next build on beta.

**Comment by magey** [comment]
I ran a test with 264 hit rating and no hit talents which gave me ~8.05% +hit chance:

![image](https://user-images.githubusercontent.com/44882404/182716350-e16dc404-6f69-4afc-826f-74a029f9ee50.png)

Hitting a level 83 Heroic Training Dummy for [5011 attacks](https://github.com/magey/wotlk-warrior/files/9255221/hitter_and_ghoul_8.05_hit_vs_boss_dummy.txt) there were 0 misses. If the bug wasn't fixed, the chance for a miss to *not* occur over 5011 attacks would be:

$\huge (1 - \frac{9 - 8.0512380599976}{100})^{5011} \approx 1.79\mathrm{e}{-21}$

Which is `~0.000000000000000000179%`, so we can conclude the bug is fixed in build 44930.
