### ISSUE TITLE
Slam is blocking the swing timer instead of suspending it

### ISSUE THREAD

**Issue by magey** [magey/wotlk-warrior#19]
WotLK made Slam no longer reset your swing, but instead just suspend it ([patch notes](https://gist.github.com/magey/dcfe8818889e30af9c97345a43976dfd#file-wotlk-patch-txt-L8899)):

```
* Slam now suspends the weapon swing timer rather than resetting it.
```

Testing on the beta (build 44644) revealed that Slam is working incorrectly; it does not suspend your swing timer when you use it, but it can block your melee swing completely if you are casting Slam right when your swing is supposed to go off.

Here are some examples with a 3.70 speed weapon:

---

![image](https://user-images.githubusercontent.com/44882404/179853024-535a1f1b-0f4b-490d-a786-a4e487fc45ec.png)

In this screenshot I auto attack a few times without doing anything, and then I am weaving untalented Slam (so 1.5s cast) between auto attacks but being careful not to still be casting Slam when my auto attack is supposed to go off. If we calculate the time between my auto attacks when I am using Slam we get:

```
00:37:45.164 - 00:37:41.453 = 3.711
00:37:52.579 - 00:37:48.816 = 3.763
00:37:59.986 - 00:37:56.282 = 3.704
```

Which shows that Slam did not suspend the swing timer when I used it in-between auto attacks.

---

![image](https://user-images.githubusercontent.com/44882404/179854090-ef1b874e-70fe-4a57-9c59-8986eeebe43b.png)

In this screenshot I auto attack a few times without doing anything, and then I am purposefully casting Slam so it clips my auto attack (I begin casting it when I have ~1s left on my swing timer) and then I let the next auto attack go off without casting Slam. If we calculate the time between my auto attacks when I am using Slam we get:

```
00:45:08.029 - 00:45:00.690 = 7.339
00:45:15.512 - 00:45:08.029 = 7.483
00:45:22.910 - 00:45:15.512 = 7.398
```

The intervals are roughly twice my attack speed (`3.70 * 2`) which shows that Slam basically stopped my auto attack from going off but the next one after that went off when it was supposed to.

**Comment by Aggrend** [comment]
This should be fixed in next week's beta build (eta 8/17).
