### ISSUE TITLE
Armored to the Teeth does not add attack power

### ISSUE THREAD

**Issue by marrowwow** [magey/wotlk-warrior#2]
#### 1.1. Description
Armored to the Teeth is supposed to add attack power to our characters based on:

AP = (Armor/108) * talentRank

Where talentRank is 1,2,3 depending on how many points have been spent on the talent.

  #### 1.2. How to Reproduce
           1. Start with the talent at 0 points. Write down your attack power.
           2. Add one point.
           3. Check your attack power (it should not have changed).
           
#### 2.1. Description
Attack power should increase with armor based on the formula above.

Tested on Version: 3.4.0.44369

**Comment by magey** [comment]
Fixed in build 45043.
