### ISSUE TITLE
Glyph of Overpower has no effect

### ISSUE THREAD

**Issue by marrowwow** [magey/wotlk-warrior#3]
#### 1.1. Description
Glyph of Overpower is supposed to allow the player to Overpower after one of his/her attacks is parried. At the moment, it does not work.

  #### 1.2. How to Reproduce
           1. Equip/utilize glyph of Overpower.
           2. Hit a player or mob until one of your attacks is parried.
           3. Attempt to use Overpower
           
#### 2.1. Description

With the Glyph equipped, players should be able to Overpower after having one of their attacks parried.

Tested on Version: 3.4.0.44369.

Video evidence to come.

**Comment by magey** [comment]
Can confirm this still happens on 44644, attached a short clip

https://user-images.githubusercontent.com/44882404/178884525-e730e49e-4e22-477c-850b-934a1f17bb83.mp4

**Comment by magey** [comment]
Fixed in build 44930.
