### ISSUE TITLE
Can't use Overpower following a Taste for Blood proc

### ISSUE THREAD

**Issue by Beannaa** [magey/wotlk-warrior#7]
#### 1.1. Description
The Taste for Blood talent currently "procs" Overpower when Rend ticks - Overpower! shows in the floating combat text, the Overpower icon glows - however pressing Overpower does not work.

  #### 1.2. How to Reproduce
           1. Spec 3/3 Taste for Blood in Arms.
           2. Cast rend on a target or dummy.
           3. Attempt to use Overpower when Taste for Blood procs Overpower.
           
#### 2.1. Description

Rend has 100% chance of making Overpower usable every 6 seconds when specced into 3/3 Taste for Blood and Overpower can be used for 9 seconds.

Tested on Version: 3.4.0.44369.

**Comment by marrowwow** [comment]
~~Seems like OP is not working at all at the moment, whether it is procced by TfB, Parries (Glyph of OP), or regular means.~~

EDIT: Beanna is reporting that OP does indeed work from dodges. OP procs from TfB and Glyph still do not work.

**Comment by magey** [comment]
Fixed in build 44930.
